DATASET:
  TRAIN:
    TYPE: 'coco_wholebody'
    ROOT: '/mnt/project2/home/ee318062/AlphaPose-master/AlphaPose/data/coco/'
    IMG_PREFIX: 'train2017'
    ANN: 'annotations/coco_wholebody_train_v1.0.json'
    AUG:
      FLIP: true
      ROT_FACTOR: 40
      SCALE_FACTOR: 0.3
      NUM_JOINTS_HALF_BODY: 8
      PROB_HALF_BODY: -1
  VAL:
    TYPE: 'coco_wholebody'
    ROOT: '/mnt/project2/home/ee318062/AlphaPose-master/AlphaPose/data/coco/'
    IMG_PREFIX: 'val2017'
    ANN: 'annotations/coco_wholebody_val_v1.0.json'
  TEST:
    TYPE: 'coco_wholebody_det'
    ROOT: '/mnt/project2/home/ee318062/AlphaPose-master/AlphaPose/data/coco/'
    IMG_PREFIX: 'val2017'
    DET_FILE: '/mnt/project2/home/ee318062/AlphaPose-master/AlphaPose/exp/json/test_det_yolo.json'
    ANN: 'annotations/coco_wholebody_val_v1.0.json'
DATA_PRESET:
  TYPE: 'simple'
  SIGMA: 2
  NUM_JOINTS: 133
  IMAGE_SIZE:
  - 256
  - 192
  HEATMAP_SIZE:
  - 64
  - 48
MODEL:
  TYPE: 'FastPose'
  PRETRAINED: ''
  TRY_LOAD: ''
  NUM_DECONV_FILTERS:
  - 256
  - 256
  - 256
  NUM_LAYERS: 50
LOSS:
  TYPE: 'MSELoss'
DETECTOR:
  NAME: 'yolo'
  CONFIG: '/mnt/project2/home/ee318062/AlphaPose-master/AlphaPose/detector/yolo/cfg/yolov3-spp.cfg'
  WEIGHTS: '/mnt/project2/home/ee318062/AlphaPose-master/AlphaPose/detector/yolo/data/yolov3-spp.weights'
  NMS_THRES: 0.6
  CONFIDENCE: 0.05
TRAIN:
  WORLD_SIZE: 4
  BATCH_SIZE: 4
  BEGIN_EPOCH: 0
  END_EPOCH: 500
  OPTIMIZER: 'adam'
  LR: 0.001
  LR_FACTOR: 0.1
  LR_STEP:
  - 90
  - 120
  DPG_MILESTONE: 140
  DPG_STEP:
  - 160
  - 190
